[project]
name = "torch-hnsw"
version = "0.1.0"
description = "get torch installed"
requires-python = ">=3.12"
dependencies = [
    "torch==2.5.0",
    "numba==0.61rc1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
